/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vrlab_foodui_FoodUiJNI */

#ifndef _Included_vrlab_foodui_FoodUiJNI
#define _Included_vrlab_foodui_FoodUiJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vrlab_foodui_FoodUiJNI
 * Method:    FindFeatures
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vrlab_foodui_FoodUiJNI_FindFeatures
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     vrlab_foodui_FoodUiJNI
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vrlab_foodui_FoodUiJNI_getStringFromNative
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL
        Java_vrlab_foodui_FoodUiJNI_hsvMode(JNIEnv *env, jobject obj, jlong addrGray, jlong addrRgba,
                                            jintArray hsvFilterValues);


#ifdef __cplusplus
}
#endif
#endif
